### PR TITLE
Removed FocusChanged and get back to old logic for SelectedPane 

### PR DESCRIPTION
**Pull request by anovik**
Due to conflict of FocusChanged with Avalonia message boxes.

Fix for https://github.com/anovik/SmartCommander/issues/102

### CODE REVIEW

**Comment by anovik** [comment]
@Diaskhan could you please review the PR, it partly reverts your logic but according to my testing all keys/tabs are still working correctly. But now we can delete items without switching to the second pane in process.

**Comment by Diaskhan** [comment]
I wouldn recomedned to revert that,
Could U descibe bug in details ?
The problem, with hotkeys, it that commands Enter,Backspace, Delete must be binded careffuly, 
https://github.com/anovik/SmartCommander/blob/a2c2dcd561f8260c2d12cc8b00ae81ac89588a33/src/SmartCommander/Views/FilesPane.axaml.cs#L57

FilePane could be in Editing mode, when we are renaming files (in place editor).

Only way to procces that key correctly is to use dataGrid_PreviewKeyDown and
    PaneDataGrid.AddHandler(KeyDownEvent, dataGrid_PreviewKeyDown, RoutingStrategies.Tunnel);

**Comment by Diaskhan** [comment]
image

The best option to make focus on Delete Widow, when we are opennin them!

**Comment by Diaskhan** [comment]
Better solution is to refactor fix behaviour of 
https://github.com/anovik/SmartCommander/blob/a2c2dcd561f8260c2d12cc8b00ae81ac89588a33/src/SmartCommander/ViewModels/MainWindowViewModel.cs#L600

when we hit MessageBox, focus is still on mainwindow!

**Comment by anovik** [comment]
I know the focus problem in message boxes for Avalonia, it seems there is no way for now to set focus correctly.

**Comment by Diaskhan** [comment]
so what about ?
https://github.com/AvaloniaCommunity/MessageBox.Avalonia

**Comment by Diaskhan** [comment]
check new PR
https://github.com/anovik/SmartCommander/pull/106
run test the behavoiur

**Comment by anovik** [comment]
ok, I agree, let's go with changing Messagebox function. I will close this PR.

**Pull request closed without merging**
