### PR TITLE
fix MessageBox focus

### PR DESCRIPTION
**Pull request by Diaskhan**
https://github.com/AvaloniaCommunity/MessageBox.Avalonia/issues/193
Createa an issue

### CODE REVIEW

**Comment by anovik** [comment]
Thanks for creating issue, but they are quite slow in reactions so I don't believe this will be fixed soon. Let's fix it from our side.

**Review by anovik — COMMENTED** [review]
I tested this change and it works for me. Please check a couple of other messagebox occurrences in code and change them similarly. You can search by "messageBoxWindow"

**Comment by Diaskhan** [comment]
Find another places where behaviour is not expected.

Is only thing that distracting me.
Is when we create folder, focus by default Is not on TextBox.

        public void ShowInput(Window owner)
        Could u recomend something ?

**Comment by anovik** [comment]
No, I don't know how to fix TextBox focus, I guess some changes for that are necessary in message box repo. 

I am going to proceed with merging this PR, if any issues still happen, we will handle them separately.

**Review by anovik — APPROVED** [review]

**Pull request merged**
